In [2]:
import pandas as pd

In [5]:
df = pd.read_csv(r'G:\ETLAug2026\Data\emp.csv')

In [9]:
df.head()

   eno   ename  salary  deptno         doj
0   10   Amber    1000      10  2018-05-14
1    2    Amar    1000      10  2017-03-22
2    8   Sagar    1000      20  2020-11-30
3    4  Thomas    1000      10  2019-08-18
4    5    Jade    2000      10  2021-02-10

In [10]:
df1 = df['ename']

In [12]:
df1.head()

0     Amber
1      Amar
2     Sagar
3    Thomas
4      Jade
Name: ename, dtype: str

In [14]:
df2 = df[['eno','ename']]
df2.head()

   eno   ename
0   10   Amber
1    2    Amar
2    8   Sagar
3    4  Thomas
4    5    Jade

In [15]:
df2.tail()

    eno    ename
42   43    Geeta
43   44    Ashok
44   45  Sanjana
45   46    Manoj
46   47    Payal